### ISSUE TITLE
Minimal useful fast Object Pool

### ISSUE THREAD

**Issue by dadhi** [dadhi/ImTools#6]
https://gist.github.com/dadhi/091e7a1edcb2cc6e657b54fb7ba1a22d

**Comment by dadhi** [comment]
Here is the preliminary results https://twitter.com/dadhi/status/1008723775683223554

![image](https://user-images.githubusercontent.com/39516/41543871-6e3a0af2-7320-11e8-98e2-11b04d5b384f.png)

The `StackPool` is being planned to be included as solution for the issue.

**Comment by dzmitry-lahoda** [comment]
Some other pull https://github.com/dotnet/corefx/blob/56dfb8834fa50f3bc61ea9b4bfdc9dcc759b6ec9/src/System.Memory/src/System/Buffers/MemoryPool.cs

**Comment by dadhi** [comment]
added.
