### ISSUE TITLE
Add sum-types

### ISSUE THREAD

**Issue by dadhi** [dadhi/ImTools#7]
From the gist https://gist.github.com/dadhi/815cf2ef8e88b555c59be7e4be93e712

Develop roslyn analyzer to notify about missing switch cases, like this: https://github.com/dadhi/SwitchEnumAnalyzer

**Comment by dzmitry-lahoda** [comment]
Would Opt be replaced https://github.com/dadhi/ImTools/blob/56b7f53a784c3843e4299658592d7b9340153fbc/src/ImTools/ImTools.cs#L626 
? 
If not, could be it made more Union based Option Like API? 
If could not, could why be document in remarks when to use that or that.

**Comment by dzmitry-lahoda** [comment]
Sum could support structs like this (no copying):
```
    public interface ICase<T> where T: readonly struct
    {
        ref T Value { get; }
    }
```

https://github.com/dotnet/csharplang/issues/1620

**Comment by dzmitry-lahoda** [comment]
Another optional https://github.com/AArnott/ImmutableObjectGraph/blob/24eb8b7144201b91e04ea59fcbc9e216eff8bfa5/src/ImmutableObjectGraph/Optional%601.cs

**Comment by dadhi** [comment]
Done, added initial version to build upon.
